#!/bin/bash
name=$(jq -r '.name' ./data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' ./data.json | sed 's/.*/\u&/')
height=$(jq -r '.height' ./data.json)
weight=$(jq -r '.weight' ./data.json)

# format and print
formatted_weight=$(($weight/10))
formatted_height=$(awk -v h=$height 'BEGIN {printf "%.1f", h/10}')
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
